# from django.db import models
#
# # Create your models here.
#
# class Candidates(models.Model):
#
#     id=models.CharField(max_length=150)
#     full_name=models.CharField(max_length=150)
#     email=models.EmailField()
#     profile_url=models.URLField()
#     first_name=models.CharField(max_length=150)
#     last_name=models.CharField(max_length=150)
#     title=models.CharField(max_length=150)
#     avatar=models.CharField(max_length=150)
#     location=models.CharField(max_length=50)
#     address=models.CharField(max_length=150)
#     birthday=models.CharField(max_length=150)
#     summary=models.CharField(max_length=250)
#     twitter=models.CharField(max_length=70)
#     phone_1=models.CharField(max_length=25)
#     phone_1_type=models.CharField(max_length=25)
#     phone_2=models.CharField(max_length=25)
#     phone_2_type=models.CharField(max_length=25)
#     phone_3=models.CharField(max_length=25)
#     phone_3_type=models.CharField(max_length=25)
#     messenger_1=models.CharField(max_length=50)
#     messenger_1_type=models.CharField(max_length=50)
#     messenger_2=models.CharField(max_length=50)
#     messenger_2_type=models.CharField(max_length=50)
#     messenger_3=models.CharField(max_length=50)
#     messenger_3_type=models.CharField(max_length=50)
#     website_1=models.URLField()
#     website_2=models.URLField()
#     website_3=models.URLField()
#     organization_1=models.CharField(max_length=75)
#     organization_title_1=models.CharField(max_length=75)
#     organization_start_1=models.CharField(max_length=75)
#     organization_end_1=models.CharField(max_length=75)
#     organization_description_1=models.CharField(max_length=75)
#     organization_location_1=models.CharField(max_length=75)
#     organization_li_url_1=models.URLField()
#     organization_li_id_1=models.CharField(max_length=20)
#     organization_2=models.CharField(max_length=75)
#     organization_title_2=models.CharField(max_length=75)
#     organization_start_2=models.CharField(max_length=75)
#     organization_end_2=models.CharField(max_length=75)
#     organization_description_2=models.CharField(max_length=75)
#     organization_location_2=models.CharField(max_length=75)
#     organization_li_url_2=models.URLField()
#     organization_li_id_2=models.CharField(max_length=20)
#     organization_3=models.CharField(max_length=75)
#     organization_title_3=models.CharField(max_length=75)
#     organization_start_3=models.CharField(max_length=75)
#     organization_end_3=models.CharField(max_length=75)
#     organization_description_3=models.CharField(max_length=75)
#     organization_location_3=models.CharField(max_length=75)
#     organization_li_url_3=models.URLField()
#     organization_li_id_3=models.CharField(max_length=20)
#     organization_4=models.CharField(max_length=75)
#     organization_title_4=models.CharField(max_length=75)
#     organization_start_4=models.CharField(max_length=75)
#     organization_end_4=models.CharField(max_length=75)
#     organization_description_4=models.CharField(max_length=75)
#     organization_location_4=models.CharField(max_length=75)
#     organization_li_url_4=models.URLField()
#     organization_li_id_4=models.CharField(max_length=20)
#     organization_5=models.CharField(max_length=75)
#     organization_title_5=models.CharField(max_length=75)
#     organization_start_5=models.CharField(max_length=75)
#     organization_end_5=models.CharField(max_length=75)
#     organization_description_5=models.CharField(max_length=75)
#     organization_location_5=models.CharField(max_length=75)
#     organization_li_url_5=models.URLField()
#     organization_li_id_5=models.CharField(max_length=20)
#     organization_6=models.CharField(max_length=75)
#     organization_title_6=models.CharField(max_length=75)
#     organization_start_6=models.CharField(max_length=75)
#     organization_end_6=models.CharField(max_length=75)
#     organization_description_6=models.CharField(max_length=75)
#     organization_location_6=models.CharField(max_length=75)
#     organization_li_url_6=models.URLField()
#     organization_li_id_6=models.CharField(max_length=20)
#     organization_7=models.CharField(max_length=75)
#     organization_title_7=models.CharField(max_length=75)
#     organization_start_7=models.CharField(max_length=75)
#     organization_end_7=models.CharField(max_length=75)
#     organization_description_7=models.CharField(max_length=75)
#     organization_location_7=models.CharField(max_length=75)
#     organization_li_url_7=models.URLField()
#     organization_li_id_7=models.CharField(max_length=20)
#     education_1=models.CharField(max_length=75)
#     education_degree_1=models.CharField(max_length=75)
#     education_fos_1=models.CharField(max_length=75)
#     education_grade_1=models.CharField(max_length=75)
#     education_start_1=models.CharField(max_length=10)
#     education_end_1=models.CharField(max_length=10)
#     education_description_1=models.CharField(max_length=75)
#     education_2 = models.CharField(max_length=75)
#     education_degree_2 = models.CharField(max_length=75)
#     education_fos_2 = models.CharField(max_length=75)
#     education_grade_2 = models.CharField(max_length=75)
#     education_start_2 = models.CharField(max_length=10)
#     education_end_2 = models.CharField(max_length=10)
#     education_description_2 = models.CharField(max_length=75)
#     education_3 = models.CharField(max_length=75)
#     education_degree_3 = models.CharField(max_length=75)
#     education_fos_3 = models.CharField(max_length=75)
#     education_grade_3 = models.CharField(max_length=75)
#     education_start_3 = models.CharField(max_length=10)
#     education_end_3 = models.CharField(max_length=10)
#     education_description_3 = models.CharField(max_length=75)
#     skills=models.CharField(max_length=500)
#     followers=models.CharField(max_length=75)
#     relationship=models.CharField(max_length=5)
#     connected_at=models.CharField(max_length=50)
#     industry=models.CharField(max_length=50)
#     emp_id=models.AutoField(primary_key=True)
#
#     def __str__(self):
#         return self.full_name + ' - ' + self.title