# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-03 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Candidates',
            new_name='Software_Engineers',
        ),
    ]
