# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-03 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20180403_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='website_3',
            field=models.CharField(max_length=50),
        ),
    ]
