# Generated by Django 2.1a1 on 2018-06-01 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_candidates_organization_end_7'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidates',
        ),
    ]
